### ISSUE TITLE
src/nvidia/arch/nvalloc/unix/src/osapi.c:4589: broken error checking ?

### ISSUE THREAD

**Issue by dcb314** [NVIDIA/open-gpu-kernel-modules#174] opened 2022-05-14 05:28 UTC
Static analyser cppcheck says:

src/nvidia/arch/nvalloc/unix/src/osapi.c:4589:50: style: Same expression on both sides of '||'. [duplicateExpression]

Source code is

    if ((pNid == NULL) || (pNumaMemAddr == NULL) || (pNumaMemAddr == NULL))

Maybe some other input parameter should be checked ?

**Comment by maximilianovermeyer** [comment] 2022-05-14 07:24
duplicate of #55

**Comment by PAR2020** [comment] 2022-05-26 01:20
dup of PR #61

**Closed** 2022-05-27 23:56 UTC
Labels: bug
