### ISSUE TITLE
Regression in 535.43.02 beta: System freeze when changing resolution

### ISSUE THREAD

**Issue by vr-hunter** [NVIDIA/open-gpu-kernel-modules#512] opened 2023-05-31 14:58 UTC
### NVIDIA Open GPU Kernel Modules Version

535.43.02 beta

### Does this happen with the proprietary driver (of the same version) as well?

I cannot test this

### Operating System and Version

Linux Mint 21.1

### Kernel Release

5.15.0-69-generic

### Hardware: GPU

NVIDIA GeForce RTX 3070

### Describe the bug

System freezes when changing resolution. 
I can boot into the system *once* without problems (by manually setting the correct resolution / refresh rate in my cinnamon-monitors.xml). As soon as I try to change the resolution / refresh rate (either manually or by changing the monitor setup or tty) the system freezes. Frozen screen, no keyboard / mouse input. I can still access the system by ssh but cannot reboot it gracefully.

### To Reproduce

Install driver, try to change resolution.

### Bug Incidence

Always

### nvidia-bug-report.log.gz

[nvidia-bug-report.log.gz](https://github.com/NVIDIA/open-gpu-kernel-modules/files/11615547/nvidia-bug-report.log.gz)

### More Info

I am coming from 530.41.03 where the problem did not exist. However, I have one of those monitor setups that require a very high pixel clock and only started working with this recent beta.

Monitor Setup is 3 * 2560x1440 @ 144 Hz.

**Comment by amrit1711** [comment] 2023-06-02 11:19
@vr-hunter 
Thanks for writing to us.
This issue seems to be not limited to open gpu kernel modules, hence I will close this tread for better tracking of issues related open kernel modules.
However, I have requested few details on below thread to triage this issue further, looking forward to hear on the same.
https://forums.developer.nvidia.com/t/regression-in-535-43-02-beta-system-freeze-when-changing-resolution/255068

**Closed by amrit1711** 2023-06-02 11:19 UTC
Labels: bug
