### ISSUE TITLE
Error building in Linux Mint

### ISSUE THREAD

**Issue by wnstdrr** [NVIDIA/open-gpu-kernel-modules#154] opened 2022-05-13 14:51 UTC
**Describe the bug**
 Installation fails during make modules_install -j\`nproc`

**To Reproduce**
sudo make modules_install -j\`nproc`

```
make -C kernel-open modules_install
make[1]: Entering directory '/opt/open-gpu-kernel-modules/kernel-open'
make[2]: Entering directory '/usr/src/linux-headers-5.4.0-110-generic'
  INSTALL /opt/open-gpu-kernel-modules/kernel-open/nvidia-drm.ko
  INSTALL /opt/open-gpu-kernel-modules/kernel-open/nvidia-modeset.ko
  INSTALL /opt/open-gpu-kernel-modules/kernel-open/nvidia-peermem.ko
  INSTALL /opt/open-gpu-kernel-modules/kernel-open/nvidia-uvm.ko
  INSTALL /opt/open-gpu-kernel-modules/kernel-open/nvidia.ko
At main.c:160:
- SSL error:02001002:system library:fopen:No such file or directory: ../crypto/bio/bss_file.c:69
- SSL error:2006D080:BIO routines:BIO_new_file:no such file: ../crypto/bio/bss_file.c:76
sign-file: certs/signing_key.pem: No such file or directory
At main.c:160:
- SSL error:02001002:system library:fopen:No such file or directory: ../crypto/bio/bss_file.c:69
- SSL error:2006D080:BIO routines:BIO_new_file:no such file: ../crypto/bio/bss_file.c:76
sign-file: certs/signing_key.pem: No such file or directory
At main.c:160:
- SSL error:02001002:system library:fopen:No such file or directory: ../crypto/bio/bss_file.c:69
- SSL error:2006D080:BIO routines:BIO_new_file:no such file: ../crypto/bio/bss_file.c:76
sign-file: certs/signing_key.pem: No such file or directory
At main.c:160:
- SSL error:02001002:system library:fopen:No such file or directory: ../crypto/bio/bss_file.c:69
- SSL error:2006D080:BIO routines:BIO_new_file:no such file: ../crypto/bio/bss_file.c:76
sign-file: certs/signing_key.pem: No such file or directory
At main.c:160:
- SSL error:02001002:system library:fopen:No such file or directory: ../crypto/bio/bss_file.c:69
- SSL error:2006D080:BIO routines:BIO_new_file:no such file: ../crypto/bio/bss_file.c:76
sign-file: certs/signing_key.pem: No such file or directory
  DEPMOD  5.4.0-110-generic
Warning: modules_install: missing 'System.map' file. Skipping depmod.
make[2]: Leaving directory '/usr/src/linux-headers-5.4.0-110-generic'
make[1]: Leaving directory '/opt/open-gpu-kernel-modules/kernel-open'
```

**Comment by Leseratte10** [comment] 2022-05-13 14:58
That seems to be a duplicate of #38 which would be some error with your kernel module signing configs, not with this repo (at least if I understand that bug report correctly).

**Comment by wnstdrr** [comment] 2022-05-13 15:20
Ah ok, thanks for clearing this up for me. Ill look into my kernel signing configs.

**Closed** 2022-05-13 15:22 UTC
Labels: bug
