### ISSUE TITLE
compiling target nvidia-modset complains `No rule to make target nv-modeset-kernel.o_binary, needed by nv-modeset-kernel.o`

### ISSUE THREAD

**Issue by worthless443** [NVIDIA/open-gpu-kernel-modules#209] opened 2022-05-16 20:29 UTC
**Describe the bug**
 When trying to compile target `nvidia-modeset`, complains:
```
No rule to make target nv-modeset-kernel.o_binary, needed by nv-modeset-kernel.o
```
I'm only trying to compile `nvidia-modset`, however the default Makefile exits with the same error 

**To Reproduce**
clone a fresh repo, and change dir to `kernel-open` and run `make modules`
**Expected behavior**
Should complete recipe for target Nvidia-modset without errors

**Comment by aritger** [comment] 2022-05-16 20:43
As currently structured, it is expected that nv-modeset-kernel.o_binary (and nv-kernel.o_binary, for that matter) are built before invoking the build in kernel-open.  Maybe this is an odd organization, but it is currently that way

(a) because the kernel-open/Makefile is also used within the .run file, where the nv-modeset-kernel.o_binary is always already present, and

(b) it might be strange for kbuild to in turn invoke a non-kbuild build.

If you want to just build just nvidia-modeset.ko, you'll first need to do
```
make kernel-open/nvidia-modeset/nv-modeset-kernel.o_binary
```
before building within kernel-open/.

For better or worse, this is currently behaving as intended.  I'm going to go ahead and close this for now.  Sorry.

**Closed by aritger** 2022-05-16 20:43 UTC
Labels: bug, build-problem
